# Scaler for hubs
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-hubs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hubs
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for haproxy
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-haproxy
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: haproxy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for Dialog
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-dialog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dialog
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for reticulum
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-reticulum
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reticulum
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for pgbouncer
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pgbouncer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for pgbouncer-t
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pgbouncer-t
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pgbouncer-t
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
---
# Scaler for coturn
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-coturn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coturn
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
    targetAverageUtilization: 80
